Updated readme
NJACKWinterOfCode/first-timers-guide pull request #6
Opened 2018-12-04 13:24 UTC by samagragupta

Fixes : #1

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> Written myself

Written index in the README.MD with each topic title in its respective topic and a direct link to the article.

2018-12-07 13:23 UTC, dhruvapte26 requested changes

2018-12-07 13:23 UTC, the-ethan-hunt commented on README.md
> +- [Cloud_development](guides/Cloud_development)
Write `Cloud Development` instead of `Cloud_development`. Change this for all applicable topics

2018-12-07 13:23 UTC, the-ethan-hunt commented on README.md
> +- [Game Development](guides/Game Development)
Correct this. Another space character should be present to activate the link. Applicable to other non-links also

2018-12-07 13:23 UTC, the-ethan-hunt commented on README.md
> +- [agile](guides/agile)
Starting letters in uppercase for all

2018-12-07 13:23 UTC, the-ethan-hunt commented
@samagragupta I have requested some changes. Do them and we are good to merge.

2018-12-08 12:58 UTC, samagragupta commented
@the-ethan-hunt Done the changes

2018-12-09 07:16 UTC, the-ethan-hunt commented
Merging it

2018-12-09 07:16 UTC, merged